#!/usr/bin/env python
import os
import subprocess
import filecmp

baseDir = "/var/www/homelessgaffer.com/"


def gitCheckout():
    subprocess.call(["git", "--work-tree=" + baseDir, "checkout", "-f"],
                    cwd="/home/cldershem/homelessgaffer.git")


def updateRequirements():
    oldRequirements = baseDir + "tmp/requirements.txt.old"
    newRequirements = baseDir + "requirements.txt"

    f = open(oldRequirements, "w")
    subprocess.call([os.path.join(baseDir, 'venv/bin', "pip"), "freeze"],
                    stdout=f)
    f.close()
    if filecmp.cmp(oldRequirements, newRequirements) is True:
        print("No changes to requirements.txt, skipping update.")
    else:
        subprocess.call([os.path.join(baseDir, 'venv/bin', "pip"),
                        "install", "-r", newRequirements])
        print('updated requirements.txt')
    subprocess.call(["rm", oldRequirements])
    print("removed tmp/requirements.txt.old")


def restartServices():
    subprocess.call(["sudo", "-u", "cldershem", "/etc/init.d/nginx",
                    "restart"])
    print "restarted nginx"

    #subprocess.call(["sudo", "service", "uwsgi", "restart"])
    #print "restarted uwsgi"

if __name__ == '__main__':
    #gitCheckout()
    #updateRequirements()
    restartServices()
