#!/usr/bin/env python
import sys
import subprocess
import os
from flake8.hooks import git_hook

#baseDir =
#"/home/cldershem/Documents/Development/homelessgaffer.com/hg-Python/"
BASE_DIR = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
baseDir = BASE_DIR


def gitFlake8():
    """checks everything against Pep8"""

    sys.exit(git_hook(complexity=10, strict=False,
                      ignore=['E501', 'E123']))
    print('finished flake8 tests')


def updateRequirements():
    """updates requirements.txt"""

    with open(baseDir + "requirements.txt", "w") as f:
        subprocess.call([os.path.join(baseDir, 'venv/bin', "pip"),
                        "freeze"], stdout=f)
    print('updated requirements.txt')


if __name__ == '__main__':
    gitFlake8()
    updateRequirements()
