#!/usr/bin/env python
import sys
import subprocess
from flake8.hooks import git_hook

baseDir = "/home/cldershem/Documents/Development/homelessgaffer.com/hg-Python"


def gitFlake8():
    """checks everything against Pep8"""
    COMPLEXITY = 10
    STRICT = False

    sys.exit(git_hook(complexity=COMPLEXITY, strict=STRICT,
                      ignore=['E501']))


def updateRequirements():
    """updates requirements.txt"""
    cdBaseDir = "cd " + baseDir
    activateVenv = "source " + baseDir + "/venv/bin/activate"
    pipFreeze = "pip freeze > " + baseDir + "/requirements.txt.tester"

    def echoBack(words):
        subprocess("echo", words.split())

    subprocess(cdBaseDir.split())
    subprocess(activateVenv.split())
    subprocess(cdBaseDir.split())
    echoBack("actiavted virtualenv")
    subprocess(pipFreeze.split())
    echoBack("updated requirements.txt")


if __name__ == '__main__':
    gitFlake8()
    updateRequirements()
