#!/usr/bin/env python
import sys
import subprocess
import os
from flake8.hooks import git_hook

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))


def gitFlake8():
    """checks everything against Pep8"""

    sys.exit(git_hook(complexity=10, strict=False,
                      ignore=['E501', 'E123']))
    print('finished flake8 tests')


def updateRequirements():
    """updates requirements.txt"""

    with open(BASE_DIR + "/requirements.txt", "w") as f:
        subprocess.call([os.path.join(BASE_DIR, 'venv/bin', "pip"),
                        "freeze"], stdout=f)
    print('updated requirements.txt')


if __name__ == '__main__':
    updateRequirements()
    gitFlake8()
